version: '3.9'
services:
  webapp:
    image: nginx:stable-alpine
    container_name: webapp
    restart: always
    ports:
      - 8555:8555
    networks:
      - appnetwork
    deploy:
      mode: replicated
      replicas: 6
  reverseproxy:
    image: nginx:stable-alpine
    container_name: nginx
    # image: nestjs-api
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    ports:
      - 80:80
    networks:
      - appnetwork
    restart: unless-stopped
networks:
  appnetwork:
    driver: bridge